### PR TITLE
Roadmap Refactor kickstart

### PR DESCRIPTION
**Pull request by renanxcortes**
I think that since now we might have some users of the package, this PR reorganizes tobler with working API between the functions, cleaning some functions, cleaning notebooks, etc. I'll still work on this refactorization, but I think this is already worth to consider merging if you're ok with the changes.

### CODE REVIEW

**Comment by knaaptime** [comment]
at this stage i'd say its definitely ok to break things (we only have three stars, I doubt there's much of a user base :P). we can make clear that we're still in alpha and the API is subject to massive changes

**Comment by renanxcortes** [comment]
> can you remove the .ipynb_checkpoints (and maybe add them to the .gitignore) ?

hm... quick question... the way that I added in https://github.com/spatialucr/tobler/pull/30/commits/bf284ce1cc63bf70b840071bda36e3cabaf6c596 this should be inside the examples folder?

**Comment by knaaptime** [comment]
i think you [want to use](https://stackoverflow.com/questions/10712555/gitignore-all-files-of-extension-in-directory) the `**/` pattern

**Comment by renanxcortes** [comment]
Ok, I went by deleting by hand all ipynotebooks_checkpoints

**Comment by renanxcortes** [comment]
> at this stage i'd say its definitely ok to break things (we only have three stars, I doubt there's much of a user base :P). we can make clear that we're still in alpha and the API is subject to massive changes

Yes, I totally agree with that! I just tweaked this PR today after finding this vectorized rasterstats and wanted to comprise this in this set of functions.

**Pull request merged**
